# Site settings
title: Marc Nylen Peace, CMKConsulting
description: 'Marc Nylen Peace, CMKConsulting'
url: 'http://www.cmkconsulting.se'
baseurl: '/cmkconsulting.github.io/'
baseurlcv: '/cmkconsulting.github.io/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Marc Nylen Peace'
  email: marc@cmkconsulting.se
  linkedin_username:  marcpeace

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
